### ISSUE TITLE
SMTP deliverabilty is always False

### ISSUE THREAD

**Issue by utiq** [Mng-dev-ai/pyrustify#3]
I tried with a yahoo.com email address to see if the response of `is_deliverable` changes but it's always `False`
I tried with a valid email address and with a made up email address and the response is always false.
I also tried using a proxy.

**Comment by Mng-dev-ai** [comment]
yea I think SMTP handshake doesn't work with yahoo so i need to figure out another way
maybe will try something like that https://github.com/hbattat/verifyEmail/blob/master/src/VerifyEmail.php#L374

**Comment by Mng-dev-ai** [comment]
Thank you for reporting, should be fixed in 0.2.0
